name: Trunk Check
author: trunk.io
description: The official trunk.io GitHub action

branding:
  icon: check
  color: orange

inputs:
  trunk-path:
    description: Path to Trunk Launcher
    required: false

  # Deprecated, prefer using arguments with `--github-label=value`.
  label:
    description: Label to append to the check run name
    required: false

  arguments:
    description: Extra arguments to pass to trunk
    required: false

  check-mode:
    description:
      Trunk check mode. Leave unset to autodetect just changes. Set to 'all' to check the entire
      repository.
    required: false

runs:
  using: composite
  steps:
    - name: Locate trunk
      shell: bash
      run: |
        # Locate trunk
        ${GITHUB_ACTION_PATH}/locate_trunk.sh
      env:
        INPUTS_TRUNK_PATH: ${{ inputs.trunk-path }}

    - name: Determine check mode
      shell: bash
      run: |
        # Determine check mode
        ${GITHUB_ACTION_PATH}/determine_check_mode.sh
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        INPUTS_CHECK_MODE: ${{ inputs.check-mode }}

    - name: Run trunk check on pull request
      if: ${{ env.TRUNK_CHECK_MODE == 'pull_request' }}
      shell: bash
      run: |
        # Run trunk check on pull request
        ${GITHUB_ACTION_PATH}/pull_request.sh
      env:
        GITHUB_EVENT_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_EVENT_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_LABEL: ${{ inputs.label }}
        INPUTS_ARGUMENTS: ${{ inputs.arguments }}

    - name: Run trunk check on push
      if: ${{ env.TRUNK_CHECK_MODE == 'push' }}
      shell: bash
      run: |
        # Run trunk check on push
        ${GITHUB_ACTION_PATH}/push.sh
      env:
        GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        GITHUB_EVENT_AFTER: ${{ github.event.after }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_LABEL: ${{ inputs.label }}
        INPUTS_ARGUMENTS: ${{ inputs.arguments }}

    - name: Run trunk check on all
      if: ${{ env.TRUNK_CHECK_MODE == 'all' }}
      shell: bash
      run: |
        # Run trunk check on all
        ${GITHUB_ACTION_PATH}/all.sh
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_LABEL: ${{ inputs.label }}
        INPUTS_ARGUMENTS: ${{ inputs.arguments }}

    - name: Cleanup temporary files
      if: ${{ always() }}
      shell: bash
      run: |
        # Cleanup temporary files
        ${GITHUB_ACTION_PATH}/cleanup.sh
